version: '3.3'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 9100:8080

  mysql:
    build:
      context: ./docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    healthcheck:
      test: ["CMD-SHELL", "mysql --password=rootpassword --execute 'SHOW DATABASES;'"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - 9101:3306
  
  postgres:
    build:
      context: ./docker/postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRESS_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 9102:5432
